### ISSUE TITLE
MainMenu Interface missing body

### ISSUE THREAD

**Issue by luiszugasti** [luiszugasti/coe528_final#1]

**Comment by the-promised-LAN** [comment]
Need to decide how to implement personal main menu's but login and authentication are done and working. Default users are:

- John, password: admin, role: volunteer
- Joe, password: password123, role: deliveryman

**Comment by luiszugasti** [comment]
From our Slack conversation, this is how our Strategy design pattern will work, if I correctly understand!
# Strategy Pattern
We will have an abstract person placement in the main body of maininterface, where we will query the stored data array in order to make a new user. When authenticated, we will make this new user as an object, using the main menu in their instance methods. When logging out, this object is destroyed, by re-referencing a new object when logging in again. All changes saved in run time of application.
